### ISSUE TITLE
'unknown workspace' error

### ISSUE THREAD

**Issue by dshlai** [BigRoy/maya-capture-gui#6]
## Problem

Maya Version: 2016.5
Platform: Windows

I encounter 'unknown workspace' error while running from Maya 2016.5 on line 197:

`images_rule = mc.workspace("images", q=1, fre=True)`

I put a 'try' around that statement to get around the RuntimeError

**Comment by BigRoy** [comment]
I'm not able to reproduce this particular error. Do you know when this is happening in your case?

**Comment by BigRoy** [comment]
This should be fixed with #7
